[package]
name = "echo-actor"
version = "0.0.1"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wascc-actor = "0.1.0"

[profile.release]
# Optimize for small code size
opt-level = "s"
